-- =============================================================================
-- SISTEMA INTEGRADO DE GESTAO EMPRESARIAL E FINANCEIRA
-- Parte 3/3: Contabilidade, fiscal, OCR, fluxo de caixa, auditoria,
--            notificacoes, integracoes, triggers, RLS e carga inicial
-- =============================================================================
SET search_path = gestao, public;

-- =============================================================================
-- M11 - CONTABILIDADE                                 (RF-078 a RF-087)
-- =============================================================================

CREATE TABLE conta_contabil (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id          uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    conta_pai_id        uuid REFERENCES conta_contabil(id) ON DELETE RESTRICT,
    codigo              varchar(30) NOT NULL,       -- 1.1.01.001
    codigo_reduzido     varchar(15),
    nome                varchar(255) NOT NULL,
    tipo                enum_tipo_conta_contabil NOT NULL,   -- RF-079
    natureza            enum_natureza_conta NOT NULL,
    nivel               smallint NOT NULL DEFAULT 1,
    aceita_lancamento   boolean NOT NULL DEFAULT false,      -- somente contas analiticas
    codigo_referencial_sped varchar(20),
    ativo               boolean NOT NULL DEFAULT true,
    criado_em           timestamptz NOT NULL DEFAULT now(),
    atualizado_em       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_conta_contabil_codigo UNIQUE (empresa_id, codigo),
    CONSTRAINT ck_conta_contabil_nivel CHECK (nivel BETWEEN 1 AND 9)
);
CREATE INDEX ix_conta_contabil_empresa ON conta_contabil (empresa_id) WHERE ativo;

-- FKs pendentes de outros modulos
ALTER TABLE categoria_financeira ADD CONSTRAINT fk_categoria_conta_contabil
    FOREIGN KEY (conta_contabil_id) REFERENCES conta_contabil(id) ON DELETE SET NULL;
ALTER TABLE verba ADD CONSTRAINT fk_verba_conta_contabil
    FOREIGN KEY (conta_contabil_id) REFERENCES conta_contabil(id) ON DELETE SET NULL;
ALTER TABLE titulo ADD CONSTRAINT fk_titulo_conta_contabil
    FOREIGN KEY (conta_contabil_id) REFERENCES conta_contabil(id) ON DELETE SET NULL;
ALTER TABLE conta_bancaria ADD CONSTRAINT fk_conta_bancaria_conta_contabil
    FOREIGN KEY (conta_contabil_id) REFERENCES conta_contabil(id) ON DELETE SET NULL;

-- Periodos contabeis (RF-086 / RN-008)
CREATE TABLE periodo_contabil (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id          uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    exercicio           smallint NOT NULL,
    mes                 smallint NOT NULL,
    data_inicio         date NOT NULL,
    data_fim            date NOT NULL,
    status              enum_status_periodo NOT NULL DEFAULT 'ABERTO',
    fechado_em          timestamptz,
    fechado_por         uuid REFERENCES usuario(id) ON DELETE SET NULL,
    reaberto_em         timestamptz,
    reaberto_por        uuid REFERENCES usuario(id) ON DELETE SET NULL,
    motivo_reabertura   text,
    criado_em           timestamptz NOT NULL DEFAULT now(),
    atualizado_em       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_periodo_contabil UNIQUE (empresa_id, exercicio, mes),
    CONSTRAINT ck_periodo_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_periodo_datas CHECK (data_fim >= data_inicio)
);

-- Lancamento contabil (cabecalho) - RF-081 / RF-082
CREATE TABLE lancamento_contabil (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id              uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    filial_id               uuid REFERENCES filial(id) ON DELETE SET NULL,
    periodo_contabil_id     uuid REFERENCES periodo_contabil(id) ON DELETE RESTRICT,
    numero                  bigint GENERATED BY DEFAULT AS IDENTITY,
    data_lancamento         date NOT NULL,
    data_competencia        date NOT NULL,
    historico               varchar(500) NOT NULL,
    valor_total             dom_valor NOT NULL,
    origem_tipo             varchar(40),        -- TITULO_BAIXA, DOCUMENTO_FISCAL, MANUAL, ESTOQUE
    origem_id               uuid,
    documento_fiscal_id     uuid REFERENCES documento_fiscal(id) ON DELETE SET NULL,
    titulo_baixa_id         uuid REFERENCES titulo_baixa(id) ON DELETE SET NULL,
    lote                    varchar(30),
    estorno_de_id           uuid REFERENCES lancamento_contabil(id) ON DELETE SET NULL,
    estornado               boolean NOT NULL DEFAULT false,
    exportado               boolean NOT NULL DEFAULT false,      -- RF-087
    exportado_em            timestamptz,
    criado_por              uuid REFERENCES usuario(id) ON DELETE SET NULL,
    criado_em               timestamptz NOT NULL DEFAULT now(),
    atualizado_em           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_lancamento_valor CHECK (valor_total > 0)
);
CREATE INDEX ix_lancamento_competencia ON lancamento_contabil (empresa_id, data_competencia);
CREATE INDEX ix_lancamento_origem ON lancamento_contabil (empresa_id, origem_tipo, origem_id);

-- Partidas (debito/credito) - RF-080 / RF-081
CREATE TABLE lancamento_partida (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id              uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    lancamento_contabil_id  uuid NOT NULL REFERENCES lancamento_contabil(id) ON DELETE CASCADE,
    sequencia               smallint NOT NULL,
    conta_contabil_id       uuid NOT NULL REFERENCES conta_contabil(id) ON DELETE RESTRICT,
    tipo                    enum_tipo_partida NOT NULL,
    valor                   dom_valor NOT NULL,
    centro_custo_id         uuid REFERENCES centro_custo(id) ON DELETE SET NULL,
    historico_complementar  varchar(500),
    CONSTRAINT uq_lancamento_partida UNIQUE (lancamento_contabil_id, sequencia),
    CONSTRAINT ck_partida_valor CHECK (valor > 0)
);
CREATE INDEX ix_partida_conta ON lancamento_partida (conta_contabil_id);
CREATE INDEX ix_partida_lancamento ON lancamento_partida (lancamento_contabil_id);

-- =============================================================================
-- M12 - FISCAL                                        (RF-088 a RF-094)
-- =============================================================================

CREATE TABLE parametro_fiscal (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id              uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    filial_id               uuid REFERENCES filial(id) ON DELETE CASCADE,
    regime_tributario       enum_regime_tributario NOT NULL,
    vigencia_inicio         date NOT NULL,
    vigencia_fim            date,
    aliquota_simples        dom_percentual,
    aliquota_iss            dom_percentual,
    contribuinte_ipi        boolean NOT NULL DEFAULT false,
    substituto_tributario   boolean NOT NULL DEFAULT false,
    parametros_adicionais   jsonb NOT NULL DEFAULT '{}'::jsonb,
    criado_em               timestamptz NOT NULL DEFAULT now(),
    atualizado_em           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_parametro_fiscal_vigencia CHECK (vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio)
);

CREATE TABLE classificacao_fiscal (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id          uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    codigo              varchar(30) NOT NULL,
    tipo                varchar(20) NOT NULL,       -- NCM, CEST, CFOP, CST, LC116
    descricao           varchar(255) NOT NULL,
    aliquota_icms       dom_percentual,
    aliquota_ipi        dom_percentual,
    aliquota_pis        dom_percentual,
    aliquota_cofins     dom_percentual,
    ativo               boolean NOT NULL DEFAULT true,
    criado_em           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_classificacao_fiscal UNIQUE (empresa_id, tipo, codigo)
);

CREATE TABLE regra_fiscal (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id              uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    nome                    varchar(120) NOT NULL,
    prioridade              smallint NOT NULL DEFAULT 100,
    uf_origem               dom_uf,
    uf_destino              dom_uf,
    tipo_operacao           varchar(30),           -- COMPRA, VENDA, TRANSFERENCIA, DEVOLUCAO
    classificacao_fiscal_id uuid REFERENCES classificacao_fiscal(id) ON DELETE SET NULL,
    produto_id              uuid REFERENCES produto(id) ON DELETE CASCADE,
    categoria_produto_id    uuid REFERENCES categoria_produto(id) ON DELETE CASCADE,
    cfop                    varchar(4),
    cst_icms                varchar(4),
    aliquota_icms           dom_percentual,
    reducao_base_icms       dom_percentual,
    condicoes               jsonb NOT NULL DEFAULT '{}'::jsonb,
    vigencia_inicio         date NOT NULL DEFAULT current_date,
    vigencia_fim            date,
    ativo                   boolean NOT NULL DEFAULT true,
    criado_em               timestamptz NOT NULL DEFAULT now(),
    atualizado_em           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_regra_fiscal_empresa ON regra_fiscal (empresa_id, prioridade) WHERE ativo;

CREATE TABLE evento_fiscal (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id          uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    documento_fiscal_id uuid REFERENCES documento_fiscal(id) ON DELETE CASCADE,
    tipo                varchar(60) NOT NULL,      -- CANCELAMENTO, CCE, MANIFESTACAO, INUTILIZACAO
    protocolo           varchar(40),
    sequencia_evento    smallint,
    data_evento         timestamptz NOT NULL DEFAULT now(),
    justificativa       text,
    xml_conteudo        text,
    status              varchar(30) NOT NULL DEFAULT 'REGISTRADO',
    retorno             jsonb,
    criado_em           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_evento_fiscal_doc ON evento_fiscal (documento_fiscal_id);

-- =============================================================================
-- M13 - OCR E AUTOMACAO DE DOCUMENTOS                 (RF-095 a RF-100)
-- =============================================================================

CREATE TABLE ocr_processamento (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id              uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    documento_id            uuid NOT NULL REFERENCES documento(id) ON DELETE CASCADE,
    provider_id             uuid REFERENCES provider(id) ON DELETE SET NULL,
    status                  enum_status_ocr NOT NULL DEFAULT 'PENDENTE',
    texto_extraido          text,
    confianca_geral         numeric(5,2),
    -- Campos extraidos (RF-097)
    valor_extraido          dom_valor,
    data_extraida           date,
    estabelecimento_nome    varchar(255),
    estabelecimento_documento varchar(14),
    chave_documento         varchar(44),
    numero_documento        varchar(30),
    -- Sugestoes (RF-098)
    categoria_sugerida_id   uuid REFERENCES categoria_financeira(id) ON DELETE SET NULL,
    centro_custo_sugerido_id uuid REFERENCES centro_custo(id) ON DELETE SET NULL,
    parceiro_sugerido_id    uuid REFERENCES parceiro(id) ON DELETE SET NULL,
    payload_bruto           jsonb,
    -- Validacao humana (RF-099)
    validado_por            uuid REFERENCES usuario(id) ON DELETE SET NULL,
    validado_em             timestamptz,
    correcoes               jsonb,
    erro                    text,
    tentativas              smallint NOT NULL DEFAULT 0,
    criado_em               timestamptz NOT NULL DEFAULT now(),
    atualizado_em           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_ocr_status ON ocr_processamento (empresa_id, status);

-- =============================================================================
-- M14 - FLUXO DE CAIXA E PLANEJAMENTO                 (RF-101 a RF-105)
-- =============================================================================

CREATE TABLE cenario_fluxo_caixa (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id          uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    nome                varchar(120) NOT NULL,
    descricao           text,
    data_inicio         date NOT NULL,
    data_fim            date NOT NULL,
    saldo_inicial       dom_valor NOT NULL DEFAULT 0,
    premissas           jsonb NOT NULL DEFAULT '{}'::jsonb,
    base                boolean NOT NULL DEFAULT false,
    criado_por          uuid REFERENCES usuario(id) ON DELETE SET NULL,
    criado_em           timestamptz NOT NULL DEFAULT now(),
    atualizado_em       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_cenario_datas CHECK (data_fim >= data_inicio)
);

CREATE TABLE projecao_fluxo_caixa (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id              uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    cenario_id              uuid REFERENCES cenario_fluxo_caixa(id) ON DELETE CASCADE,
    data_referencia         date NOT NULL,
    tipo                    enum_tipo_titulo NOT NULL,
    situacao                enum_realizacao NOT NULL,
    categoria_financeira_id uuid REFERENCES categoria_financeira(id) ON DELETE SET NULL,
    centro_custo_id         uuid REFERENCES centro_custo(id) ON DELETE SET NULL,
    valor                   dom_valor NOT NULL,
    descricao               varchar(255),
    manual                  boolean NOT NULL DEFAULT false,
    criado_em               timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_projecao_data ON projecao_fluxo_caixa (empresa_id, data_referencia);

CREATE TABLE alerta_caixa (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id          uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    conta_bancaria_id   uuid REFERENCES conta_bancaria(id) ON DELETE CASCADE,
    saldo_minimo        dom_valor NOT NULL,
    dias_antecedencia   smallint NOT NULL DEFAULT 7,
    ativo               boolean NOT NULL DEFAULT true,
    criado_em           timestamptz NOT NULL DEFAULT now()
);

-- Fluxo de caixa consolidado (RF-101 / RF-103)
CREATE OR REPLACE VIEW vw_fluxo_caixa AS
SELECT t.empresa_id,
       t.filial_id,
       p.data_vencimento                    AS data_referencia,
       t.tipo,
       t.categoria_financeira_id,
       t.centro_custo_id,
       CASE
           WHEN p.status = 'LIQUIDADA' THEN 'REALIZADO'::enum_realizacao
           WHEN p.data_vencimento < current_date THEN 'VENCIDO'::enum_realizacao
           ELSE 'PREVISTO'::enum_realizacao
       END                                   AS situacao,
       CASE WHEN p.status = 'LIQUIDADA' THEN p.valor_liquidado ELSE p.saldo END AS valor
FROM titulo_parcela p
JOIN titulo t ON t.id = p.titulo_id
WHERE t.status <> 'CANCELADO'
  AND p.status <> 'CANCELADA';

-- =============================================================================
-- M16 - AUDITORIA                                     (RF-114 a RF-118)
-- =============================================================================

CREATE TABLE auditoria (
    id                  bigint GENERATED ALWAYS AS IDENTITY,
    empresa_id          uuid,
    usuario_id          uuid,
    usuario_nome        varchar(255),
    evento              enum_tipo_evento_auditoria NOT NULL,
    entidade            varchar(60) NOT NULL,
    entidade_id         uuid,
    valor_anterior      jsonb,            -- RF-116
    valor_posterior     jsonb,
    campos_alterados    text[],
    origem              varchar(40),      -- API, WORKER, WEBHOOK, IMPORTACAO, SISTEMA
    ip                  inet,
    user_agent          text,
    correlation_id      varchar(60),
    observacao          text,
    ocorrido_em         timestamptz NOT NULL DEFAULT now(),
    -- Em tabela particionada a PK precisa conter a chave de particionamento
    PRIMARY KEY (id, ocorrido_em)
) PARTITION BY RANGE (ocorrido_em);

-- Particoes iniciais (criar novas mensalmente via job de manutencao)
CREATE TABLE auditoria_2026m08 PARTITION OF auditoria
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE auditoria_2026m09 PARTITION OF auditoria
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE auditoria_default PARTITION OF auditoria DEFAULT;

CREATE INDEX ix_auditoria_entidade ON auditoria (empresa_id, entidade, entidade_id, ocorrido_em DESC);
CREATE INDEX ix_auditoria_usuario  ON auditoria (usuario_id, ocorrido_em DESC);
COMMENT ON TABLE auditoria IS 'RF-118 / RN-010 - append-only; UPDATE e DELETE bloqueados por trigger.';

-- RF-118: protecao contra alteracao
CREATE OR REPLACE FUNCTION fn_bloqueia_alteracao_auditoria() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Registros de auditoria nao podem ser alterados ou removidos (RF-118).';
END;
$$;

CREATE TRIGGER trg_auditoria_imutavel
    BEFORE UPDATE OR DELETE ON auditoria
    FOR EACH ROW EXECUTE FUNCTION fn_bloqueia_alteracao_auditoria();

-- Trigger generico de auditoria (aplicar nas tabelas criticas)
CREATE OR REPLACE FUNCTION fn_auditoria_generica() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_anterior  jsonb;
    v_posterior jsonb;
    v_evento    enum_tipo_evento_auditoria;
    v_campos    text[];
    v_empresa   uuid;
BEGIN
    IF TG_OP = 'INSERT' THEN
        v_evento := 'CRIACAO';
        v_posterior := to_jsonb(NEW);
    ELSIF TG_OP = 'UPDATE' THEN
        v_evento := 'ALTERACAO';
        v_anterior := to_jsonb(OLD);
        v_posterior := to_jsonb(NEW);
        SELECT array_agg(chave)
          INTO v_campos
          FROM jsonb_each(v_posterior) AS n(chave, valor)
         WHERE v_anterior -> n.chave IS DISTINCT FROM n.valor;
    ELSE
        v_evento := 'EXCLUSAO';
        v_anterior := to_jsonb(OLD);
    END IF;

    v_empresa := coalesce((v_posterior ->> 'empresa_id')::uuid,
                          (v_anterior  ->> 'empresa_id')::uuid,
                          fn_empresa_corrente());

    INSERT INTO auditoria (empresa_id, usuario_id, evento, entidade, entidade_id,
                           valor_anterior, valor_posterior, campos_alterados,
                           origem, correlation_id)
    VALUES (v_empresa,
            fn_usuario_corrente(),
            v_evento,
            TG_TABLE_NAME,
            coalesce((v_posterior ->> 'id')::uuid, (v_anterior ->> 'id')::uuid),
            v_anterior,
            v_posterior,
            v_campos,
            coalesce(current_setting('app.origem', true), 'API'),
            current_setting('app.correlation_id', true));

    RETURN coalesce(NEW, OLD);
END;
$$;

-- =============================================================================
-- M17 - NOTIFICACOES E AUTOMACAO                      (RF-119 a RF-125)
-- =============================================================================

CREATE TABLE notificacao (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id          uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    usuario_id          uuid REFERENCES usuario(id) ON DELETE CASCADE,
    canal               enum_canal_notificacao NOT NULL DEFAULT 'INTERNO',
    tipo                varchar(60) NOT NULL,     -- VENCIMENTO, PAGAMENTO_FALHOU, APROVACAO_PENDENTE, DIVERGENCIA
    titulo              varchar(255) NOT NULL,
    mensagem            text NOT NULL,
    prioridade          smallint NOT NULL DEFAULT 3,
    entidade            varchar(60),
    entidade_id         uuid,
    link                text,
    status              enum_status_notificacao NOT NULL DEFAULT 'PENDENTE',
    destinatario_email  dom_email,
    enviada_em          timestamptz,
    lida_em             timestamptz,
    erro                text,
    tentativas          smallint NOT NULL DEFAULT 0,
    criado_em           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_notificacao_usuario ON notificacao (usuario_id, status, criado_em DESC);

CREATE TABLE regra_automacao (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id          uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    nome                varchar(120) NOT NULL,
    descricao           text,
    evento_gatilho      varchar(80) NOT NULL,     -- TITULO_VENCENDO, PAGAMENTO_FALHOU, DOC_FISCAL_IMPORTADO
    condicoes           jsonb NOT NULL DEFAULT '{}'::jsonb,
    acoes               jsonb NOT NULL,           -- [{"tipo":"NOTIFICAR","canal":"EMAIL","perfis":["FINANCEIRO"]}]
    agendamento_cron    varchar(60),
    ativo               boolean NOT NULL DEFAULT true,
    ultima_execucao_em  timestamptz,
    criado_em           timestamptz NOT NULL DEFAULT now(),
    atualizado_em       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_regra_automacao UNIQUE (empresa_id, nome)
);

CREATE TABLE regra_automacao_execucao (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id          uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    regra_automacao_id  uuid NOT NULL REFERENCES regra_automacao(id) ON DELETE CASCADE,
    status              enum_status_job NOT NULL DEFAULT 'PENDENTE',
    entidade_id         uuid,
    resultado           jsonb,
    erro                text,
    executado_em        timestamptz NOT NULL DEFAULT now()
);

-- =============================================================================
-- M18 - ADMINISTRACAO E INTEGRACOES                   (RF-126 a RF-131)
-- =============================================================================

CREATE TABLE integracao (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id          uuid NOT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    provider_id         uuid NOT NULL REFERENCES provider(id) ON DELETE RESTRICT,
    credencial_id       uuid REFERENCES credencial_integracao(id) ON DELETE SET NULL,
    nome                varchar(120) NOT NULL,
    status              enum_status_integracao NOT NULL DEFAULT 'ATIVA',
    configuracao        jsonb NOT NULL DEFAULT '{}'::jsonb,
    url_base            text,
    url_webhook         text,
    ultima_sincronizacao_em timestamptz,
    ultimo_erro_em      timestamptz,
    ultimo_erro         text,
    total_sucesso       bigint NOT NULL DEFAULT 0,
    total_falha         bigint NOT NULL DEFAULT 0,
    criado_em           timestamptz NOT NULL DEFAULT now(),
    atualizado_em       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_integracao UNIQUE (empresa_id, provider_id, nome)
);

CREATE TABLE integracao_log (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    empresa_id          uuid REFERENCES empresa(id) ON DELETE CASCADE,
    integracao_id       uuid REFERENCES integracao(id) ON DELETE CASCADE,
    operacao            varchar(80) NOT NULL,
    metodo_http         varchar(10),
    url                 text,
    status_http         smallint,
    sucesso             boolean NOT NULL DEFAULT false,
    duracao_ms          integer,
    request_resumo      jsonb,
    response_resumo     jsonb,
    codigo_erro         varchar(60),
    mensagem_erro       text,
    correlation_id      varchar(60),
    reprocessavel       boolean NOT NULL DEFAULT false,
    reprocessado_em     timestamptz,
    criado_em           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_integracao_log_integracao ON integracao_log (integracao_id, criado_em DESC);
CREATE INDEX ix_integracao_log_erro ON integracao_log (empresa_id, criado_em DESC) WHERE NOT sucesso;

-- =============================================================================
-- RELATORIOS CONTABEIS (RF-083, RF-084, RF-085)
-- =============================================================================

-- Razao contabil
CREATE OR REPLACE VIEW vw_razao_contabil AS
SELECT lp.empresa_id,
       cc.id                AS conta_contabil_id,
       cc.codigo            AS conta_codigo,
       cc.nome              AS conta_nome,
       lc.data_competencia,
       lc.numero            AS lancamento_numero,
       lc.historico,
       lp.tipo,
       CASE WHEN lp.tipo = 'DEBITO'  THEN lp.valor ELSE 0 END AS valor_debito,
       CASE WHEN lp.tipo = 'CREDITO' THEN lp.valor ELSE 0 END AS valor_credito,
       lp.centro_custo_id,
       lc.origem_tipo,
       lc.origem_id
FROM lancamento_partida lp
JOIN lancamento_contabil lc ON lc.id = lp.lancamento_contabil_id
JOIN conta_contabil cc      ON cc.id = lp.conta_contabil_id
WHERE NOT lc.estornado;

-- Balancete
CREATE OR REPLACE VIEW vw_balancete AS
SELECT r.empresa_id,
       r.conta_contabil_id,
       r.conta_codigo,
       r.conta_nome,
       date_trunc('month', r.data_competencia)::date AS competencia,
       sum(r.valor_debito)  AS total_debito,
       sum(r.valor_credito) AS total_credito,
       sum(r.valor_debito) - sum(r.valor_credito) AS saldo
FROM vw_razao_contabil r
GROUP BY r.empresa_id, r.conta_contabil_id, r.conta_codigo, r.conta_nome,
         date_trunc('month', r.data_competencia);

-- DRE (base: contas de resultado)
CREATE OR REPLACE VIEW vw_dre AS
SELECT b.empresa_id,
       b.competencia,
       cc.tipo,
       cc.codigo,
       cc.nome,
       CASE WHEN cc.tipo = 'RECEITA' THEN (b.total_credito - b.total_debito)
            ELSE (b.total_debito - b.total_credito) END AS valor
FROM vw_balancete b
JOIN conta_contabil cc ON cc.id = b.conta_contabil_id
WHERE cc.tipo IN ('RECEITA','DESPESA','CUSTO');

-- =============================================================================
-- TRIGGERS DE atualizado_em
-- =============================================================================
DO $$
DECLARE r record;
BEGIN
    FOR r IN
        SELECT c.table_name
        FROM information_schema.columns c
        JOIN information_schema.tables t
          ON t.table_schema = c.table_schema AND t.table_name = c.table_name
        WHERE c.table_schema = 'gestao'
          AND c.column_name = 'atualizado_em'
          AND t.table_type = 'BASE TABLE'
    LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_%1$s_atualizado_em BEFORE UPDATE ON gestao.%1$I
             FOR EACH ROW EXECUTE FUNCTION gestao.fn_set_atualizado_em();', r.table_name);
    END LOOP;
END $$;

-- =============================================================================
-- TRIGGERS DE AUDITORIA NAS ENTIDADES CRITICAS (RN-010)
-- =============================================================================
DO $$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'empresa','usuario','usuario_empresa','perfil_permissao','alcada','aprovacao',
        'parceiro','produto','pedido_compra','recebimento','documento_fiscal',
        'titulo','titulo_parcela','titulo_baixa','conta_bancaria','transacao_pagamento',
        'conciliacao','lancamento_contabil','periodo_contabil','integracao','credencial_integracao'
    ] LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_%1$s_auditoria AFTER INSERT OR UPDATE OR DELETE ON gestao.%1$I
             FOR EACH ROW EXECUTE FUNCTION gestao.fn_auditoria_generica();', t);
    END LOOP;
END $$;

-- =============================================================================
-- REGRAS DE NEGOCIO IMPLEMENTADAS NO BANCO
-- =============================================================================

-- RN-008: periodo fechado bloqueia lancamentos incompativeis
CREATE OR REPLACE FUNCTION fn_valida_periodo_fechado() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE v_status enum_status_periodo;
BEGIN
    SELECT p.status INTO v_status
      FROM periodo_contabil p
     WHERE p.empresa_id = NEW.empresa_id
       AND NEW.data_competencia BETWEEN p.data_inicio AND p.data_fim;

    IF v_status = 'FECHADO' THEN
        RAISE EXCEPTION 'Periodo contabil fechado para a competencia % (RN-008).', NEW.data_competencia;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_lancamento_periodo_fechado
    BEFORE INSERT OR UPDATE ON lancamento_contabil
    FOR EACH ROW EXECUTE FUNCTION fn_valida_periodo_fechado();

-- Partidas dobradas: soma de debitos = soma de creditos
CREATE OR REPLACE FUNCTION fn_valida_partidas_dobradas() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_debito  dom_valor;
    v_credito dom_valor;
    v_lanc    uuid := coalesce(NEW.lancamento_contabil_id, OLD.lancamento_contabil_id);
BEGIN
    SELECT coalesce(sum(valor) FILTER (WHERE tipo = 'DEBITO'), 0),
           coalesce(sum(valor) FILTER (WHERE tipo = 'CREDITO'), 0)
      INTO v_debito, v_credito
      FROM lancamento_partida
     WHERE lancamento_contabil_id = v_lanc;

    IF v_debito <> v_credito THEN
        RAISE EXCEPTION 'Lancamento % desbalanceado: debito % <> credito %.', v_lanc, v_debito, v_credito;
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_partidas_dobradas
    AFTER INSERT OR UPDATE OR DELETE ON lancamento_partida
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION fn_valida_partidas_dobradas();

-- Somente contas analiticas aceitam lancamento
CREATE OR REPLACE FUNCTION fn_valida_conta_analitica() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE v_aceita boolean;
BEGIN
    SELECT aceita_lancamento INTO v_aceita FROM conta_contabil WHERE id = NEW.conta_contabil_id;
    IF NOT coalesce(v_aceita, false) THEN
        RAISE EXCEPTION 'Conta contabil sintetica nao aceita lancamento direto.';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_partida_conta_analitica
    BEFORE INSERT OR UPDATE ON lancamento_partida
    FOR EACH ROW EXECUTE FUNCTION fn_valida_conta_analitica();

-- Recalculo de saldos do titulo/parcela apos baixa (RF-057 / RF-058)
CREATE OR REPLACE FUNCTION fn_recalcula_saldos_titulo() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_parcela uuid := coalesce(NEW.titulo_parcela_id, OLD.titulo_parcela_id);
    v_titulo  uuid;
BEGIN
    UPDATE titulo_parcela p
       SET valor_liquidado = sub.liquidado,
           saldo           = greatest(p.valor + p.valor_juros + p.valor_multa - p.valor_desconto - sub.liquidado, 0),
           status = CASE
                        WHEN sub.liquidado >= (p.valor + p.valor_juros + p.valor_multa - p.valor_desconto) THEN 'LIQUIDADA'::enum_status_parcela
                        WHEN sub.liquidado > 0 THEN 'PARCIALMENTE_LIQUIDADA'::enum_status_parcela
                        ELSE 'ABERTA'::enum_status_parcela
                    END,
           data_liquidacao = sub.ultima_baixa
      FROM (
            SELECT coalesce(sum(b.valor_principal + b.valor_juros + b.valor_multa - b.valor_desconto), 0) AS liquidado,
                   max(b.data_baixa) AS ultima_baixa
              FROM titulo_baixa b
             WHERE b.titulo_parcela_id = v_parcela
               AND NOT b.estornada
           ) sub
     WHERE p.id = v_parcela
    RETURNING p.titulo_id INTO v_titulo;

    UPDATE titulo t
       SET valor_liquidado = sub.liquidado,
           saldo           = greatest(t.valor_liquido - sub.liquidado, 0),
           status = CASE
                        WHEN t.status = 'CANCELADO' THEN t.status
                        WHEN sub.liquidado >= t.valor_liquido THEN 'LIQUIDADO'::enum_status_titulo
                        WHEN sub.liquidado > 0 THEN 'PARCIALMENTE_LIQUIDADO'::enum_status_titulo
                        ELSE 'ABERTO'::enum_status_titulo
                    END
      FROM (
            SELECT coalesce(sum(p.valor_liquidado), 0) AS liquidado
              FROM titulo_parcela p
             WHERE p.titulo_id = v_titulo
           ) sub
     WHERE t.id = v_titulo;

    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_recalcula_saldos_titulo
    AFTER INSERT OR UPDATE OR DELETE ON titulo_baixa
    FOR EACH ROW EXECUTE FUNCTION fn_recalcula_saldos_titulo();

-- Atualizacao de saldo de estoque a partir do movimento (RF-031 / RF-032)
CREATE OR REPLACE FUNCTION fn_aplica_movimento_estoque() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE v_delta dom_quantidade;
BEGIN
    v_delta := CASE
        WHEN NEW.tipo IN ('ENTRADA','TRANSFERENCIA_ENTRADA','AJUSTE_POSITIVO') THEN NEW.quantidade
        WHEN NEW.tipo IN ('SAIDA','TRANSFERENCIA_SAIDA','AJUSTE_NEGATIVO')     THEN -NEW.quantidade
        ELSE 0
    END;

    INSERT INTO estoque_saldo (empresa_id, produto_id, local_estoque_id, quantidade, custo_medio, valor_total)
    VALUES (NEW.empresa_id, NEW.produto_id, NEW.local_estoque_id, v_delta, NEW.custo_unitario,
            v_delta * NEW.custo_unitario)
    ON CONFLICT (produto_id, local_estoque_id) DO UPDATE
       SET quantidade    = estoque_saldo.quantidade + v_delta,
           custo_medio   = CASE
                               WHEN v_delta > 0 AND (estoque_saldo.quantidade + v_delta) > 0
                                   THEN ((estoque_saldo.quantidade * estoque_saldo.custo_medio)
                                         + (v_delta * NEW.custo_unitario))
                                        / (estoque_saldo.quantidade + v_delta)
                               ELSE estoque_saldo.custo_medio
                           END,
           valor_total   = (estoque_saldo.quantidade + v_delta) * estoque_saldo.custo_medio,
           atualizado_em = now();

    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_aplica_movimento_estoque
    AFTER INSERT ON movimento_estoque
    FOR EACH ROW EXECUTE FUNCTION fn_aplica_movimento_estoque();

-- =============================================================================
-- ROW LEVEL SECURITY - ISOLAMENTO MULTIEMPRESA (RF-005 / RN-001 / RN-002)
-- =============================================================================
-- A aplicacao deve executar, por requisicao:
--     SET LOCAL app.empresa_id = '<uuid>';
--     SET LOCAL app.usuario_id = '<uuid>';

CREATE ROLE app_gestao NOLOGIN;
GRANT USAGE ON SCHEMA gestao TO app_gestao;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gestao TO app_gestao;
ALTER DEFAULT PRIVILEGES IN SCHEMA gestao
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_gestao;

DO $$
DECLARE r record;
BEGIN
    FOR r IN
        SELECT c.table_name
        FROM information_schema.columns c
        JOIN information_schema.tables t
          ON t.table_schema = c.table_schema AND t.table_name = c.table_name
        WHERE c.table_schema = 'gestao'
          AND c.column_name = 'empresa_id'
          AND t.table_type = 'BASE TABLE'
          AND c.table_name <> 'auditoria'
    LOOP
        EXECUTE format('ALTER TABLE gestao.%I ENABLE ROW LEVEL SECURITY;', r.table_name);
        EXECUTE format('ALTER TABLE gestao.%I FORCE ROW LEVEL SECURITY;', r.table_name);
        EXECUTE format(
            'CREATE POLICY pol_%1$s_tenant ON gestao.%1$I
             USING (empresa_id = gestao.fn_empresa_corrente() OR empresa_id IS NULL)
             WITH CHECK (empresa_id = gestao.fn_empresa_corrente() OR empresa_id IS NULL);', r.table_name);
    END LOOP;
END $$;

-- =============================================================================
-- CARGA INICIAL MINIMA
-- =============================================================================

INSERT INTO permissao (modulo, recurso, acao, descricao) VALUES
 ('EMPRESAS','EMPRESA','LER','Consultar empresas'),
 ('EMPRESAS','EMPRESA','ESCREVER','Criar e editar empresas'),
 ('USUARIOS','USUARIO','LER','Consultar usuarios'),
 ('USUARIOS','USUARIO','ESCREVER','Criar e editar usuarios'),
 ('USUARIOS','PERFIL','ESCREVER','Gerenciar perfis e permissoes'),
 ('RH','FUNCIONARIO','LER','Consultar funcionarios'),
 ('RH','FUNCIONARIO','ESCREVER','Manter funcionarios'),
 ('RH','REEMBOLSO','APROVAR','Aprovar reembolsos'),
 ('COMPRAS','PEDIDO','LER','Consultar pedidos de compra'),
 ('COMPRAS','PEDIDO','ESCREVER','Criar e editar pedidos'),
 ('COMPRAS','PEDIDO','APROVAR','Aprovar pedidos de compra'),
 ('ESTOQUE','MOVIMENTO','ESCREVER','Movimentar estoque'),
 ('FISCAL','DOCUMENTO','LER','Consultar documentos fiscais'),
 ('FISCAL','DOCUMENTO','ESCREVER','Importar e processar documentos'),
 ('FINANCEIRO','TITULO','LER','Consultar titulos'),
 ('FINANCEIRO','TITULO','ESCREVER','Criar e editar titulos'),
 ('FINANCEIRO','TITULO','APROVAR','Aprovar titulos'),
 ('FINANCEIRO','BAIXA','ESCREVER','Registrar pagamentos e recebimentos'),
 ('BANCOS','CONTA_BANCARIA','ESCREVER','Gerenciar contas bancarias'),
 ('BANCOS','PAGAMENTO','EXECUTAR','Executar pagamentos'),
 ('BANCOS','CONCILIACAO','ESCREVER','Conciliar transacoes'),
 ('CONTABIL','LANCAMENTO','ESCREVER','Registrar lancamentos contabeis'),
 ('CONTABIL','PERIODO','FECHAR','Fechar e reabrir periodos'),
 ('RELATORIOS','RELATORIO','EXPORTAR','Exportar relatorios'),
 ('AUDITORIA','TRILHA','LER','Consultar trilhas de auditoria'),
 ('ADMIN','INTEGRACAO','ESCREVER','Administrar integracoes')
ON CONFLICT DO NOTHING;

INSERT INTO perfil (empresa_id, nome, descricao, sistema) VALUES
 (NULL,'ADMINISTRADOR','Configuracao, usuarios, permissoes e integracoes', true),
 (NULL,'DIRETOR','Visao gerencial e aprovacoes', true),
 (NULL,'FINANCEIRO','Contas, pagamentos, recebimentos e conciliacao', true),
 (NULL,'COMPRAS','Fornecedores, pedidos, recebimentos e documentos', true),
 (NULL,'RH','Funcionarios, despesas e reembolsos', true),
 (NULL,'CONTABILIDADE','Classificacao, lancamentos e relatorios contabeis', true),
 (NULL,'FISCAL','Documentos e informacoes fiscais', true),
 (NULL,'AUDITOR','Consulta de trilhas de auditoria', true),
 (NULL,'OPERACIONAL','Execucao das operacoes autorizadas', true)
ON CONFLICT DO NOTHING;

-- Administrador recebe todas as permissoes
INSERT INTO perfil_permissao (perfil_id, permissao_id)
SELECT p.id, pm.id
FROM perfil p CROSS JOIN permissao pm
WHERE p.nome = 'ADMINISTRADOR' AND p.empresa_id IS NULL
ON CONFLICT DO NOTHING;

INSERT INTO provider (codigo, nome, categoria, capacidades) VALUES
 ('MANUAL','Lancamento manual','OUTRO','{}'),
 ('BANCO_GENERICO','Provedor bancario generico','BANCARIO','{"pix":true,"boleto":true,"ted":true,"cancelamento":true,"webhook":true}'),
 ('OCR_GENERICO','Provedor de OCR generico','OCR','{"pdf":true,"imagem":true}')
ON CONFLICT DO NOTHING;
